export const projects = [
  {
    id: 1,
    category: "architecture",
    title: "Pefka 7",
    type: "New Build",
    year: "2022-",
    location: "Pefka/ Retziki, Greece",
    client: "Farlalis Building",
    status: "In Progress",
    size: 520,
  },
  {
    id: 2,
    filter: "architecture",
    title: "Pefka 7",
    type: "New Build",
    year: "2022-",
    location: "Pefka/ Retziki, Greece",
    client: "Farlalis Building",
    status: "In Progress",
    size: 520,
  },
  {
    id: 3,
    filter: "architecture",
    title: "Pefka 7",
    type: "New Build",
    year: "2022-",
    location: "Pefka/ Retziki, Greece",
    client: "Farlalis Building",
    status: "In Progress",
    size: 520,
  },
];
