export const projects = [
  {
    id: 1,
    category: "architecture",
    title: "Pefka-7",
    type: "New Build",
    year: "2022-",
    location: "Pefka/ Retziki, Greece",
    client: "Farlalis Building",
    status: "In Progress",
    size: 520,
    pictures: [
      "src/pictures/pefka-7/camera_1.0060_small.webp",
      "src/pictures/pefka-7/camera_8.0060_small.webp",
    ],
  },
  // {
  //   id: 2,
  //   filter: "architecture",
  //   title: "Pefka_8",
  //   type: "New Build",
  //   year: "2022-",
  //   location: "Pefka/ Retziki, Greece",
  //   client: "Farlalis Building",
  //   status: "In Progress",
  //   size: 520,
  //   pictures: [
  //     "src/pictures/pefka-7/camera_1.0060_small.webp",
  //     "src/pictures/pefka-7/camera_8.0060_small.webp",
  //   ],
  // },
  // {
  //   id: 3,
  //   filter: "architecture",
  //   title: "Pefka_9",
  //   type: "New Build",
  //   year: "2022-",
  //   location: "Pefka/ Retziki, Greece",
  //   client: "Farlalis Building",
  //   status: "In Progress",
  //   size: 520,
  //   pictures: [
  //     "src/pictures/pefka-7/camera_1.0060_small.webp",
  //     "src/pictures/pefka-7/camera_8.0060_small.webp",
  //   ],
  // },
];
